### ISSUE TITLE
Change GithubActions Workflow

### ISSUE THREAD

**Issue by geekypandey** [geekypandey/cf_tracker#10]
Since, the data is now present as a submodule, change the Github actions to accommodate this changes.
Steps:
- Remove the fetch contests code.
- The deploy workflow should occur only when new contests are added.
- Use of `repository_dispatch`. Read more [here](https://blog.marcnuri.com/triggering-github-actions-across-different-repositories)

Workflow:
- GithubActions run at [Codeforces Contest Data Repository](https://github.com/geekypandey/codeforces_contest_data)
- If new contests are fetched, send a post request to this repository for deploy action to take place.
- else do nothing.

**Comment by geekypandey** [comment]
Updated github action:
```yml
name: Deploy on Github Pages

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Build and Deploy
        run: |
          npm ci
          npm run build
          cd dist
          echo "cf-tracker.tech" > CNAME
          git config --global user.name "Github Actions Bot"
          git config --global user.email "<>"
          git init .
          git add -A
          git commit -m 'new build'
          git push -f https://geekypandey:${{secrets.GITHUB_TOKEN}}@github.com/geekypandey/cf_tracker.git master:gh-pages
```

But issue with submodule not found. 
Try [this](https://stackoverflow.com/questions/65077036/how-to-checkout-submodule-in-github-action)
